# -*- coding: utf-8 -*-
"""Problem statement 1 of NYRA .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P018T0T6xPav1aXCI__ku2RPRE4-LWzI
"""

import pandas as pd
import numpy as np

data=pd.read_csv("/content/edited complete.csv",encoding='latin1')

data.head()

"""data.shape"""

data.shape

data.isnull().sum()

data = data.dropna(how='any',axis=0)

data.isnull().sum()

